# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/liqinghua/eric/NodeDeploy/MATRIXNode.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1167, 918)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(20, 20, 921, 281))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.GenerateA1 = QtWidgets.QPushButton(self.frame)
        self.GenerateA1.setGeometry(QtCore.QRect(670, 50, 131, 51))
        self.GenerateA1.setObjectName("GenerateA1")
        self.ValidatorradioButton = QtWidgets.QRadioButton(self.frame)
        self.ValidatorradioButton.setGeometry(QtCore.QRect(170, 120, 61, 20))
        self.ValidatorradioButton.setObjectName("ValidatorradioButton")
        self.VDepositValue = QtWidgets.QLineEdit(self.frame)
        self.VDepositValue.setGeometry(QtCore.QRect(240, 120, 141, 21))
        self.VDepositValue.setObjectName("VDepositValue")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 0, 51, 21))
        self.label_3.setObjectName("label_3")
        self.WalletAddress = QtWidgets.QLineEdit(self.frame)
        self.WalletAddress.setGeometry(QtCore.QRect(90, 10, 571, 21))
        self.WalletAddress.setObjectName("WalletAddress")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(20, 40, 51, 21))
        self.label_10.setObjectName("label_10")
        self.entrustAccount = QtWidgets.QLineEdit(self.frame)
        self.entrustAccount.setGeometry(QtCore.QRect(90, 50, 571, 21))
        self.entrustAccount.setObjectName("entrustAccount")
        self.CloseWallet = QtWidgets.QPushButton(self.frame)
        self.CloseWallet.setGeometry(QtCore.QRect(800, 0, 121, 51))
        self.CloseWallet.setObjectName("CloseWallet")
        self.ConfirmWalletOP = QtWidgets.QPushButton(self.frame)
        self.ConfirmWalletOP.setGeometry(QtCore.QRect(670, 100, 131, 61))
        self.ConfirmWalletOP.setObjectName("ConfirmWalletOP")
        self.OpenWallet = QtWidgets.QPushButton(self.frame)
        self.OpenWallet.setGeometry(QtCore.QRect(670, 0, 131, 51))
        self.OpenWallet.setObjectName("OpenWallet")
        self.AutoCloseWallet = QtWidgets.QCheckBox(self.frame)
        self.AutoCloseWallet.setGeometry(QtCore.QRect(800, 50, 101, 20))
        self.AutoCloseWallet.setObjectName("AutoCloseWallet")
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setGeometry(QtCore.QRect(10, 80, 661, 141))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.Current2Fixed = QtWidgets.QPushButton(self.frame_10)
        self.Current2Fixed.setGeometry(QtCore.QRect(470, 70, 91, 31))
        self.Current2Fixed.setObjectName("Current2Fixed")
        self.FollowSuperNode = QtWidgets.QRadioButton(self.frame_10)
        self.FollowSuperNode.setGeometry(QtCore.QRect(20, 80, 100, 51))
        self.FollowSuperNode.setObjectName("FollowSuperNode")
        self.Fixed3MradioButton = QtWidgets.QRadioButton(self.frame_10)
        self.Fixed3MradioButton.setGeometry(QtCore.QRect(410, 40, 61, 20))
        self.Fixed3MradioButton.setObjectName("Fixed3MradioButton")
        self.Fixed6MradioButton = QtWidgets.QRadioButton(self.frame_10)
        self.Fixed6MradioButton.setGeometry(QtCore.QRect(480, 20, 61, 20))
        self.Fixed6MradioButton.setObjectName("Fixed6MradioButton")
        self.CurrentradioButton = QtWidgets.QRadioButton(self.frame_10)
        self.CurrentradioButton.setGeometry(QtCore.QRect(410, 70, 61, 20))
        self.CurrentradioButton.setObjectName("CurrentradioButton")
        self.Deposit = QtWidgets.QPushButton(self.frame_10)
        self.Deposit.setGeometry(QtCore.QRect(570, 10, 81, 41))
        self.Deposit.setObjectName("Deposit")
        self.DecreaseDeposit = QtWidgets.QPushButton(self.frame_10)
        self.DecreaseDeposit.setGeometry(QtCore.QRect(570, 50, 81, 41))
        self.DecreaseDeposit.setObjectName("DecreaseDeposit")
        self.Fixed1MradioButton = QtWidgets.QRadioButton(self.frame_10)
        self.Fixed1MradioButton.setGeometry(QtCore.QRect(410, 20, 61, 20))
        self.Fixed1MradioButton.setObjectName("Fixed1MradioButton")
        self.Fixed12Mradiobutton = QtWidgets.QRadioButton(self.frame_10)
        self.Fixed12Mradiobutton.setGeometry(QtCore.QRect(480, 40, 61, 20))
        self.Fixed12Mradiobutton.setObjectName("Fixed12Mradiobutton")
        self.WorkAccount = QtWidgets.QLineEdit(self.frame_10)
        self.WorkAccount.setGeometry(QtCore.QRect(140, 100, 511, 21))
        self.WorkAccount.setObjectName("WorkAccount")
        self.CreateSuperNode = QtWidgets.QRadioButton(self.frame_10)
        self.CreateSuperNode.setGeometry(QtCore.QRect(20, 30, 100, 51))
        self.CreateSuperNode.setObjectName("CreateSuperNode")
        self.NormalNode = QtWidgets.QRadioButton(self.frame_10)
        self.NormalNode.setGeometry(QtCore.QRect(20, 0, 100, 31))
        self.NormalNode.setObjectName("NormalNode")
        self.MDepositValue = QtWidgets.QLineEdit(self.frame_10)
        self.MDepositValue.setGeometry(QtCore.QRect(230, 10, 141, 21))
        self.MDepositValue.setObjectName("MDepositValue")
        self.MinerradioButton = QtWidgets.QRadioButton(self.frame_10)
        self.MinerradioButton.setGeometry(QtCore.QRect(160, 10, 51, 20))
        self.MinerradioButton.setObjectName("MinerradioButton")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(540, 230, 51, 21))
        self.label_9.setObjectName("label_9")
        self.frame_11 = QtWidgets.QFrame(self.frame)
        self.frame_11.setGeometry(QtCore.QRect(10, 230, 881, 41))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.TransferWalletAddress = QtWidgets.QLineEdit(self.frame_11)
        self.TransferWalletAddress.setGeometry(QtCore.QRect(70, 10, 431, 21))
        self.TransferWalletAddress.setObjectName("TransferWalletAddress")
        self.label_4 = QtWidgets.QLabel(self.frame_11)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 51, 21))
        self.label_4.setObjectName("label_4")
        self.TransferCash = QtWidgets.QPushButton(self.frame_11)
        self.TransferCash.setGeometry(QtCore.QRect(770, 0, 101, 41))
        self.TransferCash.setObjectName("TransferCash")
        self.TransferValue = QtWidgets.QLineEdit(self.frame_11)
        self.TransferValue.setGeometry(QtCore.QRect(590, 10, 141, 21))
        self.TransferValue.setObjectName("TransferValue")
        self.frame_11.raise_()
        self.frame_10.raise_()
        self.GenerateA1.raise_()
        self.ValidatorradioButton.raise_()
        self.VDepositValue.raise_()
        self.label_3.raise_()
        self.WalletAddress.raise_()
        self.label_10.raise_()
        self.entrustAccount.raise_()
        self.CloseWallet.raise_()
        self.ConfirmWalletOP.raise_()
        self.OpenWallet.raise_()
        self.AutoCloseWallet.raise_()
        self.label_9.raise_()
        self.frame_2 = QtWidgets.QFrame(self.centralWidget)
        self.frame_2.setGeometry(QtCore.QRect(960, 10, 191, 114))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.DownloadTools = QtWidgets.QPushButton(self.frame_2)
        self.DownloadTools.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DownloadTools.setObjectName("DownloadTools")
        self.verticalLayout.addWidget(self.DownloadTools)
        self.NodeInit = QtWidgets.QPushButton(self.frame_2)
        self.NodeInit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.NodeInit.setObjectName("NodeInit")
        self.verticalLayout.addWidget(self.NodeInit)
        self.NewNodeDepoly = QtWidgets.QPushButton(self.frame_2)
        self.NewNodeDepoly.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.NewNodeDepoly.setObjectName("NewNodeDepoly")
        self.verticalLayout.addWidget(self.NewNodeDepoly)
        self.frame_3 = QtWidgets.QFrame(self.centralWidget)
        self.frame_3.setGeometry(QtCore.QRect(960, 370, 191, 161))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.CheckPunish = QtWidgets.QPushButton(self.frame_3)
        self.CheckPunish.setGeometry(QtCore.QRect(20, 90, 151, 32))
        self.CheckPunish.setObjectName("CheckPunish")
        self.CheckNodeConnection = QtWidgets.QPushButton(self.frame_3)
        self.CheckNodeConnection.setGeometry(QtCore.QRect(20, 60, 151, 32))
        self.CheckNodeConnection.setObjectName("CheckNodeConnection")
        self.CheckNodeSyncNTP = QtWidgets.QPushButton(self.frame_3)
        self.CheckNodeSyncNTP.setGeometry(QtCore.QRect(20, 120, 151, 32))
        self.CheckNodeSyncNTP.setObjectName("CheckNodeSyncNTP")
        self.CheckNodeSyncStatus = QtWidgets.QPushButton(self.frame_3)
        self.CheckNodeSyncStatus.setGeometry(QtCore.QRect(20, 10, 151, 32))
        self.CheckNodeSyncStatus.setObjectName("CheckNodeSyncStatus")
        self.labelCurrentBlockHeight = QtWidgets.QLabel(self.frame_3)
        self.labelCurrentBlockHeight.setGeometry(QtCore.QRect(20, 40, 161, 21))
        self.labelCurrentBlockHeight.setObjectName("labelCurrentBlockHeight")
        self.frame_4 = QtWidgets.QFrame(self.centralWidget)
        self.frame_4.setGeometry(QtCore.QRect(960, 540, 191, 111))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.OpenExplorer = QtWidgets.QPushButton(self.frame_4)
        self.OpenExplorer.setGeometry(QtCore.QRect(20, 10, 151, 32))
        self.OpenExplorer.setObjectName("OpenExplorer")
        self.OpenExplorerWallet = QtWidgets.QPushButton(self.frame_4)
        self.OpenExplorerWallet.setGeometry(QtCore.QRect(20, 40, 151, 32))
        self.OpenExplorerWallet.setObjectName("OpenExplorerWallet")
        self.OpenExplorerAccount = QtWidgets.QPushButton(self.frame_4)
        self.OpenExplorerAccount.setGeometry(QtCore.QRect(20, 70, 151, 32))
        self.OpenExplorerAccount.setObjectName("OpenExplorerAccount")
        self.frame_6 = QtWidgets.QFrame(self.centralWidget)
        self.frame_6.setGeometry(QtCore.QRect(20, 310, 921, 161))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setGeometry(QtCore.QRect(30, 20, 101, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setGeometry(QtCore.QRect(30, 70, 101, 20))
        self.label_7.setObjectName("label_7")
        self.listWidget = QtWidgets.QListWidget(self.frame_6)
        self.listWidget.setGeometry(QtCore.QRect(120, 70, 771, 81))
        self.listWidget.setObjectName("listWidget")
        self.cmdLogText = QtWidgets.QPlainTextEdit(self.frame_6)
        self.cmdLogText.setGeometry(QtCore.QRect(120, 10, 771, 51))
        self.cmdLogText.setObjectName("cmdLogText")
        self.frame_7 = QtWidgets.QFrame(self.centralWidget)
        self.frame_7.setGeometry(QtCore.QRect(20, 480, 921, 351))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.NodeBootLogText = QtWidgets.QTextBrowser(self.frame_7)
        self.NodeBootLogText.setGeometry(QtCore.QRect(20, 30, 871, 201))
        self.NodeBootLogText.setObjectName("NodeBootLogText")
        self.NodeServiceText = QtWidgets.QTextBrowser(self.frame_7)
        self.NodeServiceText.setGeometry(QtCore.QRect(20, 260, 871, 81))
        self.NodeServiceText.setObjectName("NodeServiceText")
        self.label = QtWidgets.QLabel(self.frame_7)
        self.label.setGeometry(QtCore.QRect(20, 10, 81, 20))
        self.label.setObjectName("label")
        self.NodeStartLogRefresh = QtWidgets.QPushButton(self.frame_7)
        self.NodeStartLogRefresh.setGeometry(QtCore.QRect(110, 0, 61, 32))
        self.NodeStartLogRefresh.setObjectName("NodeStartLogRefresh")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setGeometry(QtCore.QRect(20, 240, 111, 20))
        self.label_5.setObjectName("label_5")
        self.NodeServiceRefresh = QtWidgets.QPushButton(self.frame_7)
        self.NodeServiceRefresh.setGeometry(QtCore.QRect(130, 240, 61, 32))
        self.NodeServiceRefresh.setObjectName("NodeServiceRefresh")
        self.frame_8 = QtWidgets.QFrame(self.centralWidget)
        self.frame_8.setGeometry(QtCore.QRect(20, 830, 1081, 81))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.SetDefaultWorkDir = QtWidgets.QPushButton(self.frame_8)
        self.SetDefaultWorkDir.setGeometry(QtCore.QRect(10, 10, 81, 51))
        self.SetDefaultWorkDir.setObjectName("SetDefaultWorkDir")
        self.DefaultWorkDirLabel = QtWidgets.QLabel(self.frame_8)
        self.DefaultWorkDirLabel.setGeometry(QtCore.QRect(90, 19, 421, 31))
        self.DefaultWorkDirLabel.setObjectName("DefaultWorkDirLabel")
        self.LineEditInput = QtWidgets.QLineEdit(self.frame_8)
        self.LineEditInput.setGeometry(QtCore.QRect(520, 20, 551, 31))
        self.LineEditInput.setObjectName("LineEditInput")
        self.pushButtonClearLineInput = QtWidgets.QPushButton(self.frame_8)
        self.pushButtonClearLineInput.setGeometry(QtCore.QRect(970, 50, 101, 31))
        self.pushButtonClearLineInput.setObjectName("pushButtonClearLineInput")
        self.frame_9 = QtWidgets.QFrame(self.centralWidget)
        self.frame_9.setGeometry(QtCore.QRect(960, 660, 191, 161))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.GenerateRandomAccountAddress_2 = QtWidgets.QPushButton(self.frame_9)
        self.GenerateRandomAccountAddress_2.setGeometry(QtCore.QRect(10, 120, 171, 41))
        self.GenerateRandomAccountAddress_2.setObjectName("GenerateRandomAccountAddress_2")
        self.UploadLog = QtWidgets.QPushButton(self.frame_9)
        self.UploadLog.setGeometry(QtCore.QRect(20, 60, 151, 32))
        self.UploadLog.setObjectName("UploadLog")
        self.CheckGMANVersion = QtWidgets.QPushButton(self.frame_9)
        self.CheckGMANVersion.setGeometry(QtCore.QRect(20, 30, 151, 32))
        self.CheckGMANVersion.setObjectName("CheckGMANVersion")
        self.CompileGAN = QtWidgets.QPushButton(self.frame_9)
        self.CompileGAN.setGeometry(QtCore.QRect(20, 0, 151, 32))
        self.CompileGAN.setObjectName("CompileGAN")
        self.QPushButtonexecInputCMD = QtWidgets.QPushButton(self.frame_9)
        self.QPushButtonexecInputCMD.setGeometry(QtCore.QRect(20, 90, 151, 32))
        self.QPushButtonexecInputCMD.setObjectName("QPushButtonexecInputCMD")
        self.frame_5 = QtWidgets.QFrame(self.centralWidget)
        self.frame_5.setGeometry(QtCore.QRect(960, 130, 191, 171))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.DeployMinerNode = QtWidgets.QPushButton(self.frame_5)
        self.DeployMinerNode.setGeometry(QtCore.QRect(10, 90, 177, 61))
        self.DeployMinerNode.setObjectName("DeployMinerNode")
        self.GenerateRandomAccountAddress = QtWidgets.QPushButton(self.frame_5)
        self.GenerateRandomAccountAddress.setGeometry(QtCore.QRect(10, 10, 177, 41))
        self.GenerateRandomAccountAddress.setObjectName("GenerateRandomAccountAddress")
        self.GenerateEntrustFile = QtWidgets.QPushButton(self.frame_5)
        self.GenerateEntrustFile.setGeometry(QtCore.QRect(10, 50, 177, 41))
        self.GenerateEntrustFile.setObjectName("GenerateEntrustFile")
        self.checkboxManualConfigNode = QtWidgets.QCheckBox(self.frame_5)
        self.checkboxManualConfigNode.setGeometry(QtCore.QRect(50, 140, 129, 23))
        self.checkboxManualConfigNode.setObjectName("checkboxManualConfigNode")
        self.WalletAddressLabel = QtWidgets.QLabel(self.centralWidget)
        self.WalletAddressLabel.setGeometry(QtCore.QRect(30, 0, 1071, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.WalletAddressLabel.setFont(font)
        self.WalletAddressLabel.setObjectName("WalletAddressLabel")
        self.ResetNode = QtWidgets.QPushButton(self.centralWidget)
        self.ResetNode.setGeometry(QtCore.QRect(1070, 310, 81, 51))
        self.ResetNode.setObjectName("ResetNode")
        self.StopNode = QtWidgets.QPushButton(self.centralWidget)
        self.StopNode.setGeometry(QtCore.QRect(950, 310, 121, 51))
        self.StopNode.setObjectName("StopNode")
        self.pushButtonAbout = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonAbout.setGeometry(QtCore.QRect(1100, 830, 71, 81))
        self.pushButtonAbout.setObjectName("pushButtonAbout")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(950, 0, 191, 21))
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(self.centralWidget)
        self.label_11.setGeometry(QtCore.QRect(950, 120, 201, 21))
        self.label_11.setObjectName("label_11")
        self.frame.raise_()
        self.frame_9.raise_()
        self.frame_8.raise_()
        self.frame_6.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.frame_2.raise_()
        self.frame_5.raise_()
        self.WalletAddressLabel.raise_()
        self.ResetNode.raise_()
        self.StopNode.raise_()
        self.pushButtonAbout.raise_()
        self.label_8.raise_()
        self.label_11.raise_()
        self.frame_7.raise_()
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MATRIX节点部署工具"))
        self.GenerateA1.setText(_translate("MainWindow", "无抵押账户？\n"
"生成一个随机账户"))
        self.ValidatorradioButton.setText(_translate("MainWindow", "验证者"))
        self.VDepositValue.setText(_translate("MainWindow", "验证者需高于10W"))
        self.label_3.setText(_translate("MainWindow", "钱包账户"))
        self.WalletAddress.setText(_translate("MainWindow", "MAN账户钱包地址填充，切勿输入私钥。"))
        self.label_10.setText(_translate("MainWindow", "抵押账户"))
        self.entrustAccount.setText(_translate("MainWindow", "挖矿将使用该抵押账户（委托账户，建议临时生成，注意保管密码）填充，切勿输入私钥。"))
        self.CloseWallet.setText(_translate("MainWindow", "关闭钱包\n"
"(安全第一）"))
        self.ConfirmWalletOP.setText(_translate("MainWindow", "确定抵押\n"
"（节点需同步）"))
        self.OpenWallet.setText(_translate("MainWindow", "打开钱包\n"
"(会读取私钥）"))
        self.AutoCloseWallet.setText(_translate("MainWindow", "自动关闭钱包"))
        self.Current2Fixed.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.Current2Fixed.setText(_translate("MainWindow", "活期转定期"))
        self.FollowSuperNode.setText(_translate("MainWindow", "追随他人\n"
"参加超级节点"))
        self.Fixed3MradioButton.setText(_translate("MainWindow", "3个月"))
        self.Fixed6MradioButton.setText(_translate("MainWindow", "6个月"))
        self.CurrentradioButton.setText(_translate("MainWindow", "活期"))
        self.Deposit.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.Deposit.setText(_translate("MainWindow", "抵押"))
        self.DecreaseDeposit.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.DecreaseDeposit.setText(_translate("MainWindow", "撤销抵押"))
        self.Fixed1MradioButton.setText(_translate("MainWindow", "1个月"))
        self.Fixed12Mradiobutton.setText(_translate("MainWindow", "12个月"))
        self.WorkAccount.setText(_translate("MainWindow", "输入参与的超级节点账户，请检查合法性（矿工和验证者最低为200MAN/1000MAN）"))
        self.CreateSuperNode.setText(_translate("MainWindow", "自己领头\n"
"建超级节点"))
        self.NormalNode.setText(_translate("MainWindow", "单干"))
        self.MDepositValue.setText(_translate("MainWindow", "矿工建议仅抵押1W"))
        self.MinerradioButton.setText(_translate("MainWindow", "矿工 "))
        self.label_9.setText(_translate("MainWindow", "转账金额"))
        self.TransferWalletAddress.setText(_translate("MainWindow", "请核对账户地址"))
        self.label_4.setText(_translate("MainWindow", "转账对象"))
        self.TransferCash.setText(_translate("MainWindow", "确定转账"))
        self.TransferValue.setText(_translate("MainWindow", "大额一定分批转"))
        self.DownloadTools.setToolTip(_translate("MainWindow", "从MATRIX主页下载文件，并放到当前目录下，下载后自动解压，并放在Work目录下"))
        self.DownloadTools.setText(_translate("MainWindow", "1 下载必备工具到本地"))
        self.NodeInit.setToolTip(_translate("MainWindow", "生成MAN.json文件，只需要运行一次"))
        self.NodeInit.setText(_translate("MainWindow", "2 节点初始化"))
        self.NewNodeDepoly.setToolTip(_translate("MainWindow", "启动一个观察节点，其中这个节点可以帮助同步，如果不能正确启动，请运行本框内的步骤1和2"))
        self.NewNodeDepoly.setText(_translate("MainWindow", "3 自动化部署观察节点"))
        self.CheckPunish.setToolTip(_translate("MainWindow", "检查是否在VIP选举中的黑名单。列入黑名单的原因包括端口不开，不出块等。"))
        self.CheckPunish.setText(_translate("MainWindow", "检查惩罚状态"))
        self.CheckNodeConnection.setToolTip(_translate("MainWindow", "检查本节点是否与其它节点联通"))
        self.CheckNodeConnection.setText(_translate("MainWindow", "检查联通性"))
        self.CheckNodeSyncNTP.setToolTip(_translate("MainWindow", "检查时钟是否同步，这个是节点不同步或者被列入黑名单的关键"))
        self.CheckNodeSyncNTP.setText(_translate("MainWindow", "检查时钟与NTP状态"))
        self.CheckNodeSyncStatus.setToolTip(_translate("MainWindow", "通过IPC或者RPC检查本节点的状态"))
        self.CheckNodeSyncStatus.setText(_translate("MainWindow", "检查节点同步状态"))
        self.labelCurrentBlockHeight.setText(_translate("MainWindow", "当前块高："))
        self.OpenExplorer.setToolTip(_translate("MainWindow", "打开MATRIX主页"))
        self.OpenExplorer.setText(_translate("MainWindow", "区块链浏览器预览"))
        self.OpenExplorerWallet.setToolTip(_translate("MainWindow", "打开钱包"))
        self.OpenExplorerWallet.setText(_translate("MainWindow", "在线钱包预览"))
        self.OpenExplorerAccount.setToolTip(_translate("MainWindow", "看看你有多少收益"))
        self.OpenExplorerAccount.setText(_translate("MainWindow", "个人收益预览"))
        self.label_6.setText(_translate("MainWindow", "执行的命令行："))
        self.label_7.setText(_translate("MainWindow", "命令历史记录："))
        self.cmdLogText.setStatusTip(_translate("MainWindow", "当前执行的命令，可以copy Paste"))
        self.label.setText(_translate("MainWindow", "节点启动结果"))
        self.NodeStartLogRefresh.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.NodeStartLogRefresh.setText(_translate("MainWindow", "刷新"))
        self.label_5.setText(_translate("MainWindow", "节点服务状态日志"))
        self.NodeServiceRefresh.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.NodeServiceRefresh.setText(_translate("MainWindow", "刷新"))
        self.SetDefaultWorkDir.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.SetDefaultWorkDir.setText(_translate("MainWindow", "修改默认\n"
"工作路径"))
        self.DefaultWorkDirLabel.setText(_translate("MainWindow", "默认工作路径："))
        self.LineEditInput.setText(_translate("MainWindow", "输入文本框，用于签名或者输入想要执行的命令，目的是复现各种故障"))
        self.pushButtonClearLineInput.setToolTip(_translate("MainWindow", "清除文本命令输入框"))
        self.pushButtonClearLineInput.setText(_translate("MainWindow", "clear"))
        self.GenerateRandomAccountAddress_2.setToolTip(_translate("MainWindow", "对文本框的内容签名，用于各种特殊应用"))
        self.GenerateRandomAccountAddress_2.setText(_translate("MainWindow", "钱包对输入文本框签名"))
        self.UploadLog.setToolTip(_translate("MainWindow", "上传本地debug日志"))
        self.UploadLog.setText(_translate("MainWindow", "上传诊断日志"))
        self.CheckGMANVersion.setToolTip(_translate("MainWindow", "看看是否有新版本GMAN下载"))
        self.CheckGMANVersion.setText(_translate("MainWindow", "GMAN检查更新"))
        self.CompileGAN.setToolTip(_translate("MainWindow", "下载github源码，然后编译"))
        self.CompileGAN.setText(_translate("MainWindow", "手动编译GMAN"))
        self.QPushButtonexecInputCMD.setToolTip(_translate("MainWindow", "懒得开界面窗口，直接在文本框执行命令"))
        self.QPushButtonexecInputCMD.setText(_translate("MainWindow", "执行文本框命令"))
        self.DeployMinerNode.setToolTip(_translate("MainWindow", "<html><head/><body><p>对抵押账户进行部署，并启动。记得一定选择正确的目录。目前会自动在当前目录下建立work目录，然后进入work 目录工作。</p><p>chaindata应当放到work目录下。</p><p>如果输入密码不对，会启动失败，一定记得输入正确的密码，或者手动配置后输入key密码.</p><p>如果命令不对，一定会闪退！</p><p>默认密码为：<span style=\" font-family:\'Menlo\'; font-size:18pt; color:#fc0107;\">ABCDabcd1234@1</span></p><p"))
        self.DeployMinerNode.setText(_translate("MainWindow", "3 部署挖矿节点\n"
"(使用抵押账户)"))
        self.GenerateRandomAccountAddress.setToolTip(_translate("MainWindow", "需要启动一个gman程序，然后利用IPC命令获得账户，并自动作为抵押账户，当然也可以手动输入抵押账户"))
        self.GenerateRandomAccountAddress.setText(_translate("MainWindow", "1 生成一个随机帐户"))
        self.GenerateEntrustFile.setToolTip(_translate("MainWindow", "对抵押账户的key，生成委托签名，目前用默认密码，对key.json进行加密。\n"
"如果手动输入抵押账户需要自行生成key.json"))
        self.GenerateEntrustFile.setText(_translate("MainWindow", "2 生成账户委托签名"))
        self.checkboxManualConfigNode.setText(_translate("MainWindow", "手动配置节点参数"))
        self.WalletAddressLabel.setStatusTip(_translate("MainWindow", "请检查账户，谨慎操作"))
        self.WalletAddressLabel.setText(_translate("MainWindow", "当前钱包地址无效,不操作抵押、转账功能时，无需在本区域输入任何值"))
        self.ResetNode.setToolTip(_translate("MainWindow", "启动节点，目前直接解析上一次的启动命令，然后杀死老节点，再重启。\n"
"如果更换节点，建议停止，然后选择其它启动方式"))
        self.ResetNode.setText(_translate("MainWindow", "重启节点"))
        self.StopNode.setToolTip(_translate("MainWindow", "当启动正式挖矿后，一定要停用自动部署的观察节点。其中生成随机账户需要用到节点启动"))
        self.StopNode.setText(_translate("MainWindow", "停止节点\n"
"挖矿必须新启动"))
        self.pushButtonAbout.setToolTip(_translate("MainWindow", "帮助大家使用GMAN"))
        self.pushButtonAbout.setStatusTip(_translate("MainWindow", "提供简单帮助与使用说明，包括节点部署与状态检查"))
        self.pushButtonAbout.setText(_translate("MainWindow", "Help\n"
"About"))
        self.label_8.setText(_translate("MainWindow", "全新节点，单纯观察和同步"))
        self.label_11.setText(_translate("MainWindow", "挖矿节点，如有账户，直接步骤3"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
